import Ember from 'ember';
import DS from 'ember-data';

export default DS.Model.extend({
  kind: DS.attr('string'),

  // kind: HG
  hgMetric: DS.attr('string'),

  // Metric output
  isMetricNameAutogenerated: DS.attr('boolean', {defaultValue: true}),
  metricName: DS.attr('string'),

  // Autogenerate metric name if needed
  onChange: function() {
    Ember.run.once(this, 'processOnChange');
  }.observes('hgMetric', 'isMetricNameAutogenerated'),

  processOnChange: function() {
    if (this.get('isMetricNameAutogenerated')) {
      var sanitizedHgMetric = this.get('hgMetric').replace(/[()]/g, "_");
      this.set('metricName', sanitizedHgMetric);
    }
  }
});
