language: ruby
rvm:
  - 2.1.3
before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
install:
  - cd ui && npm install -g bower
  - cd ui && npm install
  - cd ui && bower install
script:
  - bundle exec rspec
  - cd ui && ember test
services:
  - redis-server
