language: ruby
rvm:
  - 2.1.3
before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
install:
  - pushd ui && npm install -g bower && popd
  - pushd ui && npm install && popd
  - pushd ui && bower install && popd
script:
  - bundle exec rspec
  - cd ui && ember test
services:
  - redis-server
